def build(bld):
    #bld.env.append_value('LINKFLAGS',
    #                     ['-std=c++17', '-Wall', '-Werror', '-Wextra',
    #                      '-pthread'])
    bld(features = 'cxx cxxprogram',
        target = 'raw_data_test',
        source = 'raw_data_test.cpp',
        includes=['../../include/', '../../src/'],
        lib=['gtestmock'],
        libpath=['lib'],
        use = ['tartarus'])
