import sys

def build(bld):

    libs = []
    
    if sys.platform == 'linux' or sys.platform == 'linux2':
        libs.append('stdc++fs')

    bld(features = 'cxx cxxprogram',
        target = 'raw_data_test',
        source = 'raw_data_test.cpp',
        lib = libs, 
        use = ['tartarus_includes', 'tartarus', 'gtest'])
