import sys

def build(bld):

    libs = []
    link_flags = list()
    if sys.platform == 'linux' or sys.platform == 'linux2':
        libs.append('stdc++fs')

    bld(features = 'cxx cxxprogram',
        target = 'files_test',
        source = 'files_test.cpp',
        lib = libs,
        use = ['json_includes', 'tartarus_includes', 'tartarus', 'gtest'])
