def build(bld):
    bld.env.append_value('CXXFLAGS',
                         ['-std=c++17', '-Wall', '-Werror', '-Wextra',
                          '-pthread'])
    bld(features = 'cxx cxxprogram',
        target = 'raw_data_example',
        source = 'raw_data_example.cpp',
        includes = ['../../src'],
        use = ['tartarus'])
