import sys

def build(bld):

    libs = []
    
    if sys.platform == 'linux' or sys.platform == 'linux2':
        libs.append('stdc++fs')

    if sys.platform == 'darwin':
        libs.append('c++fs')
            
    bld(features = 'cxx cxxprogram',
        target = 'test_writers_and_readers',
        source = 'test_writers_and_readers.cpp',
        lib = libs, 
        use = ['tartarus_includes', 'tartarus', 'gtest'])
