import sys

def build(bld):

    libs = []
    
    if sys.platform == 'linux' or sys.platform == 'linux2':
        libs.append('stdc++fs')

    bld(features = 'cxx cxxprogram',
        target = 'test_writers_and_readers',
        source = 'test_writers_and_readers.cpp',
        lib = libs, 
        use = ['json_includes', 'tartarus_includes', 'tartarus', 'gtest'])
