import sys

def build(bld):

    libs = []
    link_flags = list()
    if sys.platform == 'linux' or sys.platform == 'linux2':
        libs.append('stdc++fs')

#    if sys.platform == 'darwin':
#        libs.append('c++fs')

    bld(features = 'cxx cxxprogram',
        target = 'files',
        source = 'files.cpp',
        lib = libs,
        use = ['tartarus_includes'])
