def build(bld):
    bld.env.append_value('CXXFLAGS',
                         ['-std=c++17', '-Wall', '-Werror', '-Wextra',
                          '-pthread'])
    bld(features = 'cxx cxxprogram',
        target = 'coded_data_test',
        source = 'coded_data_test.cpp',
        includes=['../../include/', '../../src/'],
        lib=['gtestmock'],
        libpath=['lib'],
        use = ['tartarus'])
