def build(bld):
    bld(features = 'cxx cxxprogram',
        target = 'coded_data_test',
        source = 'coded_data_test.cpp',
        libpath=['lib'],
        use = ['tartarus_includes', 'gtest'])
